### ISSUE TITLE
Dashboad Change

### ISSUE THREAD

**Issue by patellalit** [patellalit/hasani#5]
1) replace area with dealers
2) Add link on count. After click redirect to registered cdkey page and search according it.
example: Click on Gujarat count. It will redirect registered cdkey page and search Gujarat in state,
same in city and dealer
call me in morning for more information

**Comment by patellalit** [comment]
Bug:
When click on any number. No records filter under registered cdkey. From and To date filled with 1970. Please check it and solved tonight if possible.

**Comment by patellalit** [comment]
If 0 count in all columns it should not be listed on dashboad.

**Comment by patellalit** [comment]
Arrow not working properly in city , state and dealer

**Comment by patellalit** [comment]
Count in right side and plan index in left side

**Comment by patellalit** [comment]
Dashboad count issue in dealer viashal electronics

**Comment by vidhisampat2807** [comment]
All points done. 
For point "Dashboad count issue in dealer vishal electronics" : There are records with vishal electronics and vishal electronic. in dashbord records are fetch with distinct and in registered cd key menu page, records are fetch using like. so it fetch count having vishal electronics and vishal electronic both.. We cant change in dashboard. please confirm if you want to change in registered cd key menu.

call me if not getting issue

**Comment by patellalit** [comment]
Need to change each column with package and in each row should be plan.
Eample
Package 1         Package 2         Package 3         Package 4
plan 0-100         plan 0-100         plan 0-100         plan 0-100
plan 100-200     plan 100-200     plan 100-200     plan 100-200

**Comment by vidhisampat2807** [comment]
Done as discussed on phone. please check

**Comment by patellalit** [comment]
Need to change Plan index table.

All Risk Cover                Only Damage                 Iphone Care  
P1  0 - 5000    P9        0 - 5000                        P15   0 - 30000  
P2  5001 - 7000       P10   5001 - 7000           P16   30001 - 40000  
P3  7001 - 15000          P11   7001 - 15000          P17   40001 - 65000  
P4  15001 - 20000         P12   15001 - 25000         P18   65001 - 90000  
P5  20001 - 35000         P13   25001 - 40000  
P6  35001 - 50000         P14   40001 - 65000  
P7  50001 - 65000  
P8  65001 - 90000   

Need to add one field "status" (Active/Inactive) in package and plan table. Display only activce package and plans in dashboard.

**Comment by vidhisampat2807** [comment]
Done.. check

To add status field run below query

ALTER TABLE `plans` ADD `status` INT NOT NULL DEFAULT '1' COMMENT '0-inactive, 1-active' ;

**Comment by patellalit** [comment]
Its working fine
