### ISSUE TITLE
Registered CDkey Menu change

### ISSUE THREAD

**Issue by patellalit** [patellalit/hasani#6]
need to edit link after click on edit all fileds should be editable.

**Comment by patellalit** [comment]
Menu name change with Activation instead of Registration CDKey

**Comment by vidhisampat2807** [comment]
Done. please check

**Comment by patellalit** [comment]
Missing fields in edit form State, city, area missing.

**Comment by patellalit** [comment]
When I edit any record and save it. It give me PHP error.
I sent latest live Database. So please check it.

**Comment by vidhisampat2807** [comment]
latest database can not import, gives error. sent you screenshoot. ( Also attached here ). please send again
![screen shot 2015-05-17 at 8 12 04 am](https://cloud.githubusercontent.com/assets/9783449/7673051/1602ea28-fd28-11e4-9f33-11c07ebc0530.png)

**Comment by patellalit** [comment]
I solved it and commited. Take update
