### ISSUE TITLE
Pagging - record per page drop down in every list page

### ISSUE THREAD

**Issue by patellalit** [patellalit/hasani#7]
Drop down value fix - 10, 20, 30, 50, 100, 200, 500
This values popuplate from comman function. Show if we need to add/remove any value. It will changed in that function only.

Call me if any issue

**Comment by vidhisampat2807** [comment]
Done. Please Check

**Comment by patellalit** [comment]
Pagging not working properly any pages. Please TEST IT PROPER.
When I changed 10 to 20 records per page than going 2 secound or any other page. Its display same records in some pages or no records in some pages.

TRY TO IMPORT NEW DATABASE. Manuly open sql file in notepad and copy half half queries in database. I will call you tonight.

**Comment by vidhisampat2807** [comment]
check paging again

**Comment by vidhisampat2807** [comment]
sql file you sent, itself has error at bottom. it is not exported properly. please check

**Comment by patellalit** [comment]
Its working properly now.
